DROP TABLE IF EXISTS words;
DROP TABLE IF EXISTS sections;
DROP TABLE IF EXISTS dictionaries;
DROP TABLE IF EXISTS users;

DROP SEQUENCE USER_SEQ IF EXISTS;
DROP SEQUENCE DICT_SEQ IF EXISTS;
DROP SEQUENCE SECT_SEQ IF EXISTS;
DROP SEQUENCE WORD_SEQ IF EXISTS;

CREATE SEQUENCE USER_SEQ AS INTEGER START WITH 1;
CREATE SEQUENCE DICT_SEQ AS INTEGER START WITH 1;
CREATE SEQUENCE SECT_SEQ AS INTEGER START WITH 1;
CREATE SEQUENCE WORD_SEQ AS INTEGER START WITH 1;

CREATE TABLE users
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE USER_SEQ PRIMARY KEY,
    user_name        VARCHAR(100) NOT NULL,
    password         VARCHAR(100) NOT NULL,
    role             VARCHAR(10) NOT NULL
);
CREATE UNIQUE INDEX users_unique_user_name_idx ON users (user_name);

CREATE TABLE dictionaries
(
    id          INTEGER GENERATED BY DEFAULT AS SEQUENCE DICT_SEQ PRIMARY KEY,
    user_id     INTEGER NOT NULL,
    name        VARCHAR(50) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE sections
(
    id              INTEGER GENERATED BY DEFAULT AS SEQUENCE SECT_SEQ PRIMARY KEY,
    user_id         INTEGER NOT NULL,
    dictionary_id   INTEGER NOT NULL,
    name            VARCHAR(50) NOT NULL,
    FOREIGN KEY (dictionary_id) REFERENCES dictionaries (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE words
(
    id              INTEGER GENERATED BY DEFAULT AS SEQUENCE WORD_SEQ PRIMARY KEY,
    user_id         INTEGER NOT NULL,
    section_id      INTEGER NOT NULL,
    dictionary_id   INTEGER NOT NULL,
    word            VARCHAR(1000) NOT NULL,
    translation     VARCHAR(1000) NOT NULL,
    FOREIGN KEY (section_id) REFERENCES sections (id) ON DELETE CASCADE,
    FOREIGN KEY (dictionary_id) REFERENCES dictionaries (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

INSERT INTO users (user_name, password, role)
VALUES ('Admin', '0E012C5187EF01131BDC4B46DB6198FC', 'ADMIN'),
       ('DemoUser', '0E012C5187EF01131BDC4B46DB6198FC', 'USER'),
       ('Test002', '0E012C5187EF01131BDC4B46DB6198FC', 'USER');

INSERT INTO dictionaries (user_id, name)
VALUES (1, 'ADMIN_DICT_1'),
       (1, 'ADMIN_DICT_2'),
       (2, 'USER_1_DICT_1'),
       (2, 'USER_1_DICT_2'),
       (2, 'USER_1_DICT_3'),
       (3, 'USER_2_DICT_1'),
       (3, 'USER_2_DICT_2');

INSERT INTO sections (user_id, dictionary_id, name)
VALUES (1, 1, 'ADMIN_SECT_1'),
       (1, 1, 'ADMIN_SECT_2'),
       (1, 2, 'ADMIN_SECT_3'),
       (1, 2, 'ADMIN_SECT_4'),
       (2, 3, 'USER_1_SECT_1'),
       (2, 3, 'USER_1_SECT_2');

INSERT INTO words (user_id, section_id, dictionary_id, word, translation)
VALUES (1, 1, 1, 'Hello', 'Привет'),
       (1, 1, 1, 'Get', 'Получать'),
       (1, 1, 1, 'Give', 'Давать'),
       (1, 2, 1, 'Move', 'Двигаться'),
       (1, 2, 1, 'Run', 'Бежать'),
       (1, 3, 2, 'Ask', 'Задавать'),
       (1, 3, 2, 'Fill', 'Заполнять'),
       (1, 3, 2, 'Say', 'Сказать'),
       (1, 3, 2, 'Add', 'Добавить');